# Generated by Django 3.2 on 2021-11-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(default='oi', max_length=40, verbose_name='Cidade')),
                ('nomeEstadio', models.CharField(default='oi', max_length=50, verbose_name='Nome do Estadio')),
                ('donoCampo', models.CharField(default='oi', max_length=80, verbose_name='Dono do Campo')),
                ('enderecoCampo', models.CharField(default='oi', max_length=150, verbose_name='Endereço do Campo')),
                ('comprimentoCampo', models.SmallIntegerField(verbose_name='Comprimento do Campo')),
                ('larguraCampo', models.SmallIntegerField(verbose_name='Largura do Campo')),
                ('precoHora', models.PositiveSmallIntegerField(verbose_name='Preço por Hora')),
            ],
        ),
        migrations.CreateModel(
            name='PrecoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Por segurança, insira o nome do estádio aqui ')),
                ('data', models.CharField(max_length=10, verbose_name='Insira a data no formato MM/DD/YYYY ')),
            ],
        ),
    ]
