# Generated by Django 3.2.8 on 2021-10-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=40)),
                ('nomeClube', models.CharField(max_length=50)),
                ('donoCampo', models.CharField(max_length=80)),
                ('enderecoCampo', models.CharField(max_length=150)),
                ('comprimentoCampo', models.SmallIntegerField()),
                ('larguraCampo', models.SmallIntegerField()),
                ('precoHora', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
