# Generated by Django 3.2 on 2021-10-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadio',
            old_name='nomeClube',
            new_name='nomeEstadio',
        ),
    ]
