# Generated by Django 3.2 on 2021-11-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precofinal',
            name='horas',
            field=models.SmallIntegerField(default=0, verbose_name='Insira por quantas horas deseja alugar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='precofinal',
            name='data',
            field=models.CharField(max_length=10, verbose_name='Insira a data no formato MM/DD/YYYY'),
        ),
        migrations.AlterField(
            model_name='precofinal',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Por segurança, insira o nome do estádio aqui'),
        ),
    ]
