# Generated by Django 3.2 on 2021-11-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_auto_20211103_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precofinal',
            name='nome',
        ),
        migrations.AlterField(
            model_name='precofinal',
            name='data',
            field=models.CharField(max_length=10, verbose_name='Insira a data no formato DD/MM/YYYY'),
        ),
    ]
