# Generated by Django 3.2 on 2021-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_alter_precofinal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precofinal',
            name='data',
            field=models.DateField(verbose_name='Insira a data no formato MM/DD/YYYY : '),
        ),
    ]
