# Generated by Django 3.2 on 2021-10-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_rename_nomeclube_estadio_nomeestadio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DateField(verbose_name='Ano')),
            ],
        ),
        migrations.AlterField(
            model_name='estadio',
            name='cidade',
            field=models.CharField(choices=[('Valença', 'Valença'), ('Barra do Piraí', 'Barra do Piraí'), ('Paracambi', 'Paracambi'), ('Vassouras', 'Vassouras')], max_length=40, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='comprimentoCampo',
            field=models.SmallIntegerField(verbose_name='Comprimento do Campo'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='donoCampo',
            field=models.CharField(max_length=80, verbose_name='Dono do Campo'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='enderecoCampo',
            field=models.CharField(max_length=150, verbose_name='Endereço do Campo'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='larguraCampo',
            field=models.SmallIntegerField(verbose_name='Largura do Campo'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nomeEstadio',
            field=models.CharField(max_length=50, verbose_name='Nome do Estadio'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='precoHora',
            field=models.PositiveSmallIntegerField(verbose_name='Preço por Hora'),
        ),
    ]
