# Generated by Django 3.2 on 2021-11-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0003_auto_20211029_1341'),
        ('aluguel', '0004_alter_precofinal_data'),
    ]

    operations = [
    ]
