# Generated by Django 3.2 on 2021-11-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0004_precofinal_valorfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='precofinal',
            name='nome',
            field=models.CharField(default='', max_length=50, verbose_name=''),
            preserve_default=False,
        ),
    ]
