# Generated by Django 3.2 on 2021-11-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0004_alter_precofinal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='cidade',
            field=models.CharField(default='oi', max_length=40, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='donoCampo',
            field=models.CharField(default='oi', max_length=80, verbose_name='Dono do Campo'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='enderecoCampo',
            field=models.CharField(default='oi', max_length=150, verbose_name='Endereço do Campo'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nomeEstadio',
            field=models.CharField(default='oi', max_length=50, verbose_name='Nome do Estadio'),
        ),
    ]
