# Generated by Django 3.2 on 2021-11-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0005_auto_20211103_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='precofinal',
            name='estadioEscolhido',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='aluguel.estadio'),
            preserve_default=False,
        ),
    ]
