# Generated by Django 3.2 on 2021-11-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0006_precofinal_estadioescolhido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precofinal',
            name='data',
            field=models.CharField(max_length=10, verbose_name='Insira a data no formato MM/DD/YYYY: '),
        ),
        migrations.AlterField(
            model_name='precofinal',
            name='estadioEscolhido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aluguel.estadio'),
        ),
    ]
