# Generated by Django 3.2 on 2021-11-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0008_rename_estadioescolhido_precofinal_idescolhido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precofinal',
            name='idEscolhido',
        ),
        migrations.AddField(
            model_name='precofinal',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Por segurança, insira o nome do estádio aqui: '),
        ),
    ]
