# Generated by Django 3.2 on 2021-11-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0009_auto_20211103_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precofinal',
            name='data',
            field=models.CharField(max_length=10, verbose_name='Insira a data no formato MM/DD/YYYY '),
        ),
        migrations.AlterField(
            model_name='precofinal',
            name='nome',
            field=models.CharField(default='', max_length=50, verbose_name='Por segurança, insira o nome do estádio aqui '),
            preserve_default=False,
        ),
    ]
